version: '3'

services:
  web:
    depends_on:
      - postgres
    env_file: .env
    image: rubyjobsru/app
    volumes:
      - .:/home/app

  postgres:
    image: postgres:10.1
    volumes:
      - data-postgres_10_1:/var/lib/postgresql/data

volumes:
  data-postgres_10_1:
