version: '3'

services:
  web:
    depends_on:
      - postgres
    env_file: .env
    image: rubyjobsru/app
    volumes:
      - .:/home/app

  postgres:
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    image: postgres:9.6
    volumes:
      - data-postgres_9_6:/var/lib/postgresql/data

volumes:
  data-postgres_9_6:
