version: '3'

services:
  test_runner:
    depends_on:
      - postgres
    env_file: .env
    environment:
      - RAILS_ENV=test
    image: rubyjobsru/app
    volumes:
      - .:/home/app

  system_test_runner:
    depends_on:
      - selenium
      - web
    env_file: .env
    environment:
      - APP_URL=http://web:3000
      - RAILS_ENV=test
      - SELENIUM_URL=http://selenium:4444/wd/hub
    image: rubyjobsru/app
    volumes:
      - .:/home/app

  web:
    environment:
      - RAILS_ENV=test

  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - 5900:5900

  sut:
    build: .
    command: script/cibuild
