version: '3'

services:
  web:
    depends_on:
      - postgres
    env_file: .env
    image: rubyjobsru/app
    volumes:
      - .:/home/app

  postgres:
    image: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
